ToDoProject/ToDoApp/urls.py
from django.urls import path

from . import views

app_name = 'ToDoApp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('delete_todo_modal/<int:pk>/', views.DeleteToDoView.as_view(), name='delete_todo_modal'),
    path('delete_todo/<int:pk>/', views.delete_todo, name='delete_todo'),
    path('create_todo_modal/', views.CreateToDoModalView.as_view(), name='create_todo_modal'),
    path('create_todo/', views.create_todo, name='create_todo'),
    path('change_status/<int:pk>/', views.change_status, name='change_status'),
]

ToDoProject/ToDoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ToDoApp/', include('ToDoApp.urls'))
]

ToDoProject/ToDoApp/models.py
from django.db import models


# Create your models here.
class ToDo(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200, verbose_name='Title')
    description = models.CharField(max_length=500, verbose_name='Description')
    state = models.BooleanField(default=False, verbose_name='State')
    created_date = models.DateTimeField(verbose_name='Created')

    def __str__(self):
        return self.title

ToDoProject/ToDoApp/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from .models import ToDo
from datetime import datetime


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'ToDoApp/index.html'
    context_object_name = 'todo_list'

    def get_queryset(self):
        """Return the To Do items"""
        return ToDo.objects.order_by('created_date')


class DetailView(generic.DetailView):
    template_name = 'ToDoApp/detail.html'
    model = ToDo


class DeleteToDoView(generic.DetailView):
    template_name = 'ToDoApp/delete_todo_modal.html'
    model = ToDo


class CreateToDoModalView(generic.ListView):
    template_name = 'ToDoApp/create_todo_modal.html'
    model = ToDo


def create_todo(request):
    if request.method == 'POST':
        title = request.POST.get('new_title')
        description = request.POST.get('new_description')
        state = eval(request.POST.get('new_state').capitalize())

        ToDo.objects.create(
            id=(1 if ToDo.objects.count() == 0 else ToDo.objects.latest('id').id + 1),
            title=title,
            description=description,
            state=state,
            created_date=datetime.now().strftime('%Y-%m-%d %H:%M'),
        )

        return HttpResponseRedirect('/ToDoApp/')


def delete_todo(request, pk):
    if request.method == 'POST':
        obj = ToDo.objects.get(id=pk)
        obj.delete()

    return HttpResponseRedirect('/ToDoApp/')


def change_status(request, pk):
    if request.method == 'POST':
        obj = ToDo.objects.get(id=pk)
        obj.state = (not obj.state)
        obj.save()

    return HttpResponseRedirect('/ToDoApp/')

ToDoProject/templates/ToDoApp/create_todo_modal.html
<div class="container">
    <form name="create_todo_form" id="create_todo_form">
        <input type="text" name="new_title" id="new_title"/><label for="new_title"><span>Title</span></label>
        <input type="text" name="new_description" id="new_description"/><label for="new_description"><span>Description</span></label><br><br>
        <label for="new_state"><input type="checkbox" name="new_state" id="new_state"/><span>Status</span></label>
    </form>
</div>

ToDoProject/templates/ToDoApp/delete_todo_modal.html
{% csrf_token %}
Are you sure you want to delete <b>{{ todo.title }}</b> from the list?

ToDoProject/templates/ToDoApp/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>{{ todo.title }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <p>{{ todo.description }}</p>
</div>

{% endblock content %}

ToDoProject/templates/ToDoApp/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container" id="content">{% csrf_token %}
    <ul>
        {% if todo_list %}
            {% for todo in todo_list %}
                <li>
                    <div class="row">
                        {% if todo.state %}
                            <a class="left waves-effect" href="#"><i class="small material-icons" onclick="change_state({{ todo.id }})">check_box</i></a>
                        {% else %}
                            <a class="left waves-effect" href="#"><i class="small material-icons" onclick="change_state({{ todo.id }})">check_box_outline_blank</i></a>
                        {% endif %}
                        <div class="col s12 m6">
                            <div class="card blue-grey darken-1">
                                <div class="card-content white-text">
                                    <span class="card-title"><a href="{% url 'ToDoApp:detail' todo.id %}">{{ todo.title }}</a></span>
                                    <p>{{ todo.description }}</p>
                                </div>
                                <div class="card-action">
                                    <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons" onclick="delete_todo({{ todo.id }})">delete</i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        {% else %}
            <li><div class="row"><p>No To Do are available.</p></div></li>
        {% endif %}
        <li><div class="row center"><div class="col s12 m6"><a class="btn-floating btn-large waves-effect waves-light green center"><i class="material-icons" onclick="create_todo()">add</i></a></div></div></li>
    </ul>
</div>

<script>
    function delete_todo(id)
    {
        $.confirm({
            theme: "modern",
            title: 'Please confirm',
            content: 'url: delete_todo_modal/' + id + '/',
            buttons: {
                confirm: function () {
                    $.ajax({
                        type: 'POST',
                        url: 'delete_todo/' + id + '/',
                        data: {
                            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                        },
                        success: function(){
                            setTimeout(function(){// wait for 1 secs(2)
                                  location.reload(); // then reload the page.(3)
                            }, 1000);
                        }
                    });
                },
                cancel: function () {

                }
            }
        });
    };

    function create_todo()
    {
        $.confirm({
            title: 'Create new To Do',
            content: 'url:/ToDoApp/create_todo_modal/',
            buttons: {
                formSubmit: {
                    text: 'Submit',
                    btnClass: 'btn-blue',
                    action: function () {
                        $.ajax({
                            type: 'POST',
                            url: 'create_todo/',
                            data: {
                                new_title: $('input[name=new_title]').val(),
                                new_description: $('input[name=new_description]').val(),
                                new_state: $('input[name=new_state]').is(':checked'),
                                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                            },
                            success: function(){
                                  setTimeout(function(){// wait for 1 secs(2)
                                       location.reload(); // then reload the page.(3)
                                  }, 1000);
                            }
                        });
                    }
                },
                cancel: function () {
                    //close
                }
            },
            onContentReady: function () {
                $('#create_todo_form').keypress(function(e) {
                    if(e.which == 13) {
                        $('#create_todo_form').submit();
                    }
                })
                // bind to events
                var jc = this;
                this.$content.find('form').on('submit', function (e) {
                // if the user submits the form by pressing enter in the field.
                    e.preventDefault();
                    jc.$$formSubmit.trigger('click'); // reference the button and click it
                });
            }
        });
    }

    function change_state (id)
    {
        $.ajax({
            type: 'POST',
            url: 'change_status/' + id + '/',
            data: {
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(){
                setTimeout(function(){// wait for 1 secs(2)
                    location.reload(); // then reload the page.(3)
                }, 1000);
            }
        });
    }
</script>

{% endblock content %}

ToDoProject/templates/base.html
{% load static %}

<html lang="en">

    <head>
        <title>To Do List</title>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
        <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
        <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    </head>

    <body>
        <nav class="navbar">
            <div class="container nav-wrapper">
                <div class="row center">
                    <div class="col s12 m6">
                        <a href="/ToDoApp"><h4>To Do List</h4></a>
                    </div>
                </div>
            </div>
        </nav>

        {% block content %}

        {% endblock content %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    </body>
</html>